### ISSUE TITLE
Please make it possible to use the library with testcontainers

### ISSUE THREAD

**Issue by mikaevnikita** [Tradeshift/spring-rabbitmq-tuning#20]
I tried to move my project with this library,
and faced with the inability to use the library with testcontainers.
Also could you add the ability to use default properties as a connection and an exchange ?
Code:
```
@Configuration
@EnableRabbit
@Getter
public class RabbitConfig implements RabbitListenerConfigurer {
    @Value("${spring.rabbitmq.custom.create-task.exchange}")
    private String bpmEventsExchange;

    @Value("${spring.rabbitmq.custom.create-task.queue}")
    private String createTaskQueue;

    @Value("${spring.rabbitmq.custom.close-task.queue}")
    private String closeTaskQueue;

    @Value("${spring.rabbitmq.custom.create-process.queue}")
    private String createProcessQueue;

    @Value("${spring.rabbitmq.custom.close-process.queue}")
    private String closeProcessQueue;

    @Autowired
    private ObjectMapper objectMapper;

    @Bean
    @Primary
    public Jackson2JsonMessageConverter producerJackson2MessageConverter() {
        return new Jackson2JsonMessageConverter(objectMapper);
    }

    @Override
    public void configureRabbitListeners(RabbitListenerEndpointRegistrar registrar) {
        registrar.setMessageHandlerMethodFactory(messageHandlerMethodFactory());
    }

    @Bean
    @Primary
    MessageHandlerMethodFactory messageHandlerMethodFactory() {
        DefaultMessageHandlerMethodFactory messageHandlerMethodFactory = new DefaultMessageHandlerMethodFactory();
        messageHandlerMethodFactory.setMessageConverter(consumerJackson2MessageConverter());
        return messageHandlerMethodFactory;
    }

    @Bean
    @Primary
    public MappingJackson2MessageConverter consumerJackson2MessageConverter() {
        MappingJackson2MessageConverter converter = new MappingJackson2MessageConverter();
        converter.setObjectMapper(objectMapper);

        return converter;
    }
}
```

and this is my application.yml:
```
spring:
rabbitmq:
    cache:
      channel:
        size: 4
      connection:
        mode: channel
    listener:
      simple:
        acknowledge-mode: auto
        default-requeue-rejected: false
    custom:
      create-task:
        queue: q.bpms.create.task.events
        exchange: t.bpms.events
        exchangeType: direct
        virtualHost: /
        host: ${TM_RABBIT_HOST}
        port: ${TM_RABBIT_PORT}
        username: ${TM_RABBIT_USERNAME}
        password: ${TM_RABBIT_PASSWORD}
        autoCreate: true
        queueRoutingKey: q.bpms.create.task.events
        ttlRetryMessage: 15000
        maxRetriesAttempts: 3
        enableJsonMessageConverter: true
        ttlMultiply: 1
      close-task:
        queue: q.bpms.close.task.events
        exchange: t.bpms.events
        exchangeType: direct
        virtualHost: /
        host: ${TM_RABBIT_HOST}
        port: ${TM_RABBIT_PORT}
        username: ${TM_RABBIT_USERNAME}
        password: ${TM_RABBIT_PASSWORD}
        autoCreate: true
        queueRoutingKey: q.bpms.close.task.events
        ttlRetryMessage: 15000
        maxRetriesAttempts: 3
        enableJsonMessageConverter: true
        ttlMultiply: 1
      create-process:
        queue: q.bpms.create.process.events
        exchange: t.bpms.events
        exchangeType: direct
        virtualHost: /
        host: ${TM_RABBIT_HOST}
        port: ${TM_RABBIT_PORT}
        username: ${TM_RABBIT_USERNAME}
        password: ${TM_RABBIT_PASSWORD}
        autoCreate: true
        queueRoutingKey: q.bpms.create.process.events
        ttlRetryMessage: 15000
        maxRetriesAttempts: 3
        enableJsonMessageConverter: true
        ttlMultiply: 1
      close-process:
        queue: q.bpms.close.process.events
        exchange: t.bpms.events
        exchangeType: direct
        virtualHost: /
        host: ${TM_RABBIT_HOST}
        port: ${TM_RABBIT_PORT}
        username: ${TM_RABBIT_USERNAME}
        password: ${TM_RABBIT_PASSWORD}
        autoCreate: true
        queueRoutingKey: q.bpms.close.process.events
        ttlRetryMessage: 15000
        maxRetriesAttempts: 3
        enableJsonMessageConverter: true
        ttlMultiply: 1
```

And application-test.yml:
```
spring:
  rabbitmq:
      listener:
        simple:
          auto-startup: false
    custom:
      create-task:
        autoCreate: false
      close-task:
        autoCreate: false
      create-process:
        autoCreate: false
      close-process:
        autoCreate: false
```

My tests looks like:
`public class CloseProcessListenerIT extends SingletonAbstractRabbitIT`

And SingletonAbstractRabbitIT looks like this:
```
public abstract class SingletonAbstractRabbitIT extends AbstractIT {
    static {
        RabbitMQContainer rabbitMQContainer = new RabbitMQContainer("rabbitmq:3.7-management")
                .withExposedPorts(5672)
                .withVhost("/")
                .withUser("admin", "admin")
                .withPermission("/", "admin", ".*", ".*", ".*");

        rabbitMQContainer.start();

        String rabbitMqHost = rabbitMQContainer.getContainerIpAddress();
        String rabbitMqPort = rabbitMQContainer.getMappedPort(5672) + "";

        //create-task
        System.setProperty("spring.rabbitmq.custom.create-task.host", rabbitMqHost);
        System.setProperty("spring.rabbitmq.custom.create-task.port", rabbitMqPort);
        System.setProperty("spring.rabbitmq.custom.create-task.username", "admin");
        System.setProperty("spring.rabbitmq.custom.create-task.password", "admin");
        System.setProperty("spring.rabbitmq.custom.create-task.autoStartup", "true");

        //close-task
        System.setProperty("spring.rabbitmq.custom.close-task.host", rabbitMqHost);
        System.setProperty("spring.rabbitmq.custom.close-task.port", rabbitMqPort);
        System.setProperty("spring.rabbitmq.custom.close-task.username", "admin");
        System.setProperty("spring.rabbitmq.custom.close-task.password", "admin");
        System.setProperty("spring.rabbitmq.custom.close-task.autoStartup", "true");

        //create-process
        System.setProperty("spring.rabbitmq.custom.create-process.host", rabbitMqHost);
        System.setProperty("spring.rabbitmq.custom.create-process.port", rabbitMqPort);
        System.setProperty("spring.rabbitmq.custom.create-process.username", "admin");
        System.setProperty("spring.rabbitmq.custom.create-process.password", "admin");
        System.setProperty("spring.rabbitmq.custom.create-process.autoStartup", "true");

        //close-process
        System.setProperty("spring.rabbitmq.custom.close-process.host", rabbitMqHost);
        System.setProperty("spring.rabbitmq.custom.close-process.port", rabbitMqPort);
        System.setProperty("spring.rabbitmq.custom.close-process.username", "admin");
        System.setProperty("spring.rabbitmq.custom.close-process.password", "admin");
        System.setProperty("spring.rabbitmq.custom.close-process.autoStartup", "true");
    }
}
```
the configuration was no less cumbersome, but that’s not all, I get the following in the log:
`2019-08-16 18:29:03.957 ERROR 16858 --- [127.0.0.1:34522] o.s.a.r.c.CachingConnectionFactory       : Channel shutdown: channel error; protocol method: #method<channel.close>(reply-code=404, reply-text=NOT_FOUND - no exchange 't.bpms.events' in vhost '/', class-id=60, method-id=40)
`
